### ISSUE TITLE
Release for 0.9.14

### ISSUE THREAD

**Issue by mk148a** [aeonix/aeon-legacy#105]
Hi, can you build release version? I have windows machine not have cmake.

**Comment by mk148a** [comment]
ı found it release https://ci.appveyor.com/project/stoffu/aeon/build/artifacts
, but i have issue my old wallet is not worked(its created bby 0.9.13)
https://i.hizliresim.com/Dy2411.jpg

**Comment by stoffu** [comment]
As the message says: `Attempting to generate or restore wallet, but specified file(s) exist.  Exiting to not risk overwriting.`, simplewallet refuses to overwrite an existing wallet file while it's restoring a deterministic wallet. You should pass `--wallet-file <filename>` in order to open an existing wallet.

**Comment by mk148a** [comment]
no this message says" Error: failed to load wallet: failed to read file "aeon-pool" " aeon-pool is my wallet name, i think this wallet file not reading for new release

**Comment by stoffu** [comment]
I don’t see that message in the linked jpg image.

**Comment by mk148a** [comment]
Oh you are right:
https://i.hizliresim.com/Dy2BBo.jpg

**Comment by stoffu** [comment]
Thanks to @Arux-BTT I realized (https://bitcointalk.org/index.php?topic=641696.msg22788813#msg22788813) that the Windows binary on AppVeyor I posted earlier was built with Boost 1.63 which was incompatible with the official 0.9.13 Windows binary built with Boost 1.64. Now I've rebuilt the binary on AppVeyor with Boost 1.64, which should fix the problem:

- https://ci.appveyor.com/project/stoffu/aeon/build/artifacts

Please try it and report if the problem was fixed.

**Comment by devopsralf** [comment]
I have the latest windows build here: https://aeonpool.dreamitsystems.com/downloads/AEON-v0.9.14.0-Win64.zip

**Comment by mk148a** [comment]
@devopsralf yeah its worked thanks this issue is solved @stoffu

**Comment by devopsralf** [comment]
@mk148a glad to be of service. Working on a simplewallet gui for aeon as well. Stay tuned.

**Comment by iamsmooth** [comment]
The Windows binaries were uploaded to the release area some time ago
