### ISSUE TITLE
failed to handle_remote_peerlist(...)

### ISSUE THREAD

**Issue by polozhevets** [aeonix/aeon-legacy#122]
2017-Dec-18 21:33:52.460079 [P2P0]ERROR c:\users\arno\documents\github\aeon-0.9.14.0\src\p2p\net_node.inl:521 [173.32.220.220:53144 INC]COMMAND_TIMED_SYNC: failed to handle_remote_peerlist(...), closing connection.

> AEON-0.9.14.0-WIN64\aeond.exe

**Comment by qskousen** [comment]
Did it continue to sync after this? I think this is telling you that a remote node that it connected to failed to respond to a request in time so the connection was closed. If that is the case, this message can be safely ignored.

**Comment by polozhevets** [comment]
@qskousen No, its not continued yesterday. I repeated it today, and it worked. But Arno's system path should not be displayed in the console.

**Comment by qskousen** [comment]
@polozhevets Agreed, but it's displayed because you are running a pre-compiled binary and it is displaying the path that was used at compilation time. It can't reference the actual path that is used now because it doesn't have any reference to the initial source code. I don't know that there is any way around that.

**Comment by aeonix** [comment]
The time sync message likely indicates a stuck connection or failed peer. This is normal behavior. 

The issue of nodes sometimes getting stuck in syncing has other issues open
