### ISSUE TITLE
Alternative chain block

### ISSUE THREAD

**Issue by polozhevets** [aeonix/aeon-legacy#123]
2017-Dec-18 21:41:40.513528 [P2P1]**Block with id: <9135f7c24d67fc7ad618e231ce2d38f59307b50ae2b23e3aa8640f02aebf0f45>
 can't be accepted for alternative chain, block height: 406
 blockchain height: 903007**

2017-Dec-18 21:41:40.518531 [P2P1][178.21.23.35:43085 INC]Block verification failed, dropping connection

2017-Dec-18 21:41:42.476933 [P2P6][66.68.96.91:16963 INC]Sync data returned unknown top block: 903007 -> 1000 [902007 blocks ahead]

SYNCHRONIZATION started

2017-Dec-18 21:41:47.796031 [P2P6]Block with id: <9135f7c24d67fc7ad618e231ce2d38f59307b50ae2b23e3aa8640f02aebf0f45>
 can't be accepted for alternative chain, block height: 406
 blockchain height: 903007

2017-Dec-18 21:41:47.802537 [P2P6][66.68.96.91:16963 INC]Block verification failed, dropping connection

2017-Dec-18 21:41:48.807864 [P2P6]Block with id: <9135f7c24d67fc7ad618e231ce2d38f59307b50ae2b23e3aa8640f02aebf0f45>
 can't be accepted for alternative chain, block height: 406
 blockchain height: 903007

2017-Dec-18 21:41:48.814108 [P2P6][195.167.123.5:46878 INC]Block verification failed, dropping connection

**Comment by stoffu** [comment]
This message is commonly observed and totally normal. You can ignore it.

**Comment by bobbieltd** [comment]
I got same error. After dozen of minutes, it displayed “Killed”. I tried run multiple time but unsuccessful. Still not synced.

**Comment by qskousen** [comment]
Killed is usually displayed when you do Ctrl+c on a program IIRC. Did you inadvertently kill it? Can you confirm that the blockchain is not syncing at all? What platform are you running on?

**Comment by polozhevets** [comment]
![2017-12-19](https://user-images.githubusercontent.com/1768864/34175601-169ee178-e50e-11e7-8773-8a94805c748c.png)
I wonder where this block came from and why it got into the blockchain

_Actually 0.9.14.0-WIN64 version_

**Comment by bobbieltd** [comment]
Ubuntu 16.04,Linode, 4G RAM, Putty SSH. No Ctrl + C, tried removed and restarted over (Git/Make) but unsuccessful, killed by itself (see screenshot)
![aeon failed sync](https://user-images.githubusercontent.com/29669374/34176311-20f3b0da-e532-11e7-9df2-bc4c3007af52.png)

**Comment by qskousen** [comment]
@bobbieltd I believe your problem is different. "Killed" will show up in the process log if the out of memory killer kills it. aeond does not yet have all the recent improvements that have been made to monerod regarding blockchain storage and memory usage. I would bet that your 4gb of RAM is not enough for the aeond process to load the blockchain, and so it uses too much memory and Ubuntu is killing the process so the server itself doesn't crash.

**Comment by bobbieltd** [comment]
@qskousen Thank you for pointing that out. Yeah, you're right. I added 10Gb swap and it didn't get killed anymore. Syncing is very slow. 48h up to now, it's not done yet. Do you know how can I accelerate it ?

**Comment by unformatt** [comment]
Same error here on same block - but we're being told this is normal? I'm genuinely interested in how "Broken pipe", "dropping connection", "verification failed" is normal, expected behavior.

![image](https://user-images.githubusercontent.com/157132/34265942-87d79bb8-e645-11e7-86fb-80a85dcbcf14.png)


```
2017-Dec-21 11:52:27.962317 [P2P8][95.77.96.100:22837 INC]Sync data returned unknown top block: 375211 -> 1000 [374211 blocks ahead]
SYNCHRONIZATION started
2017-Dec-21 11:52:32.068207 [P2P1]Block with id: <9135f7c24d67fc7ad618e231ce2d38f59307b50ae2b23e3aa8640f02aebf0f45>
 can't be accepted for alternative chain, block height: 406
 blockchain height: 377811
2017-Dec-21 11:52:32.068252 [P2P1][95.77.96.100:22837 INC]Block verification failed, dropping connection
2017-Dec-21 11:52:33.832727 [P2P5][sock 30] Some problems at write: Broken pipe:32

```

**Comment by bobbieltd** [comment]
Is AEON dead ? Syncing comes with unbelievable number of error messages (ok, ignore them :) ). I don't know if it could take days or weeks even months to finish syncing.

**Comment by bobbieltd** [comment]
Aeond block syncing stucked at 1000 #117

**Comment by unformatt** [comment]
For anyone hoping to actually sync their wallet, use a public node: https://www.reddit.com/r/Aeon/comments/73829j/public_nodes_new_list/

e.g.
`
simplewallet --wallet-file wallet.bin --daemon-address node.aeon-wallet.net:11181
`

**Comment by stoffu** [comment]
Use of public node should be considered as merely an interim workaround when one urgently needs to send funds before fully syncing his own node. It's not a "solution" to any issues regarding node syncing.

@bobbieltd 
You may need to give it a bit more time, since you seem to be using a very low-end computer.
`aeond` is known to work quite well for typical laptops and desktops with Linux/Windows/OSX, but it might not work with some other untested hardware such as Raspberry Pi.

**Comment by aeonix** [comment]
The alternative block is not an issue. Getting stuck during sync is covered in other issues
