### ISSUE TITLE
Accidentally sent 50 aeon using a 0 mixin - it's gone now.

### ISSUE THREAD

**Issue by nutsnax** [aeonix/aeon-legacy#142]
I accidentally sent 50 aeon using a 0 mixin and simplewallet let me do it without rejecting it... the payment never made it to the other side and since hasn't come back to my wallet.

**Comment by stoffu** [comment]
Simplewallet doesn't show you a confirmation dialog, which is admittedly not very user friendly. It'll be improved once the rebase is done.

Mixin 0 txes will take a long time to get confirmed. If your tx didn't get confirmed within 24 hours, it will be dropped from the tx pool of most of the full nodes in the network, and you'll be able to make another tx again. 

You need to let simplewallet rescan the blockchain in order to mark those funds used in the failed tx as unspent. This can be done by:

1. delete the wallet cache file "mywallet" (not the other one "mywallet.keys"), and
2. open "mywallet.keys" with simplewallet

A new wallet cache file "mywallet" will be created after rescanning.

**Comment by BigslimVdub** [comment]
Just for future reference (because it will be asked for rebase) you can also delete the wallet file and run cmd window and CD to the folder location of simplewallet and run the command : simplewallet.exe --restore-deterministic-wallet

then create a new wallet name and password and enter your seed you saved from the original wallet and let it sync (took about an hour for me when I did this)

**Comment by aeonix** [comment]
Resolved
