### ISSUE TITLE
Problem of the big pools Aeon and Electroneum in the same case ?

### ISSUE THREAD

**Issue by phil2cr** [aeonix/aeon-legacy#146]
There is a commun problem here:

https://github.com/electroneum/electroneum-pool/issues/145

**Comment by stoffu** [comment]
Among those small pools listed in http://aeonpools.net/ , I don't see any pools with many orphan blocks except https://aeon.n-engine.com/#pool_blocks (which may have its own issue).

I'm also solo mining and get rewarded at the expected rate. Therefore, I don't see any problem.

**Comment by phil2cr** [comment]
Hi,
"I'm also solo mining and get rewarded at the expected rate. Therefore, I don't see any problem."
I am happy for you, but it is not our case.
I can see others littles pools (<1MH/s) struggling to get blocks.
Have a good day.

**Comment by stoffu** [comment]
> I can see others littles pools (<1MH/s) struggling to get blocks.

Which pools? Please be specific. I don't see any problems with smaller pools, for example:

![screen shot 2018-01-16 at 15 33 47](https://user-images.githubusercontent.com/26077532/34974948-d5115daa-fad2-11e7-89f0-b47962ca5371.jpg)
http://aeon.hash2mine.com (12KH/s)

![screen shot 2018-01-16 at 15 34 04](https://user-images.githubusercontent.com/26077532/34974952-dc4aa536-fad2-11e7-9fdd-d75844e136c6.jpg)
https://aeon.magiclobster.de (38KH/s)

![screen shot 2018-01-16 at 15 34 20](https://user-images.githubusercontent.com/26077532/34974968-ebeb58a0-fad2-11e7-98fe-96b65c97f7e5.jpg)
https://aeon.poolto.be (5.5KH/s)

![screen shot 2018-01-16 at 15 34 40](https://user-images.githubusercontent.com/26077532/34974976-f19d6f68-fad2-11e7-8e58-8a3d1826bd6f.jpg)
http://aeon.cryptofriends.org (5.0KH/s)

All of them show good mix of red and green, meaning that they're getting block rewards more or less at the expected rate (100%) on average. This variance has nothing to do with the pool's hash rate.

If you believe your pool is not rewarded fairly, show us a proof (e.g. consistently low block finding rate compared to the calculated one, frequent orphan blocks, etc). Otherwise, your point is invalid.

**Comment by phil2cr** [comment]
We allready discuss about that ( https://github.com/aeonix/aeon/issues/140 ), and i allready show the time problem in the blockchain.

I think it is could be a consequence to have only one or two bigs pools.

**Comment by stoffu** [comment]
#140 doesn't provide any useful information. I don't see any problems. Probably your understanding on how cryptocurrencies work is simply lacking.

Please close this thread since your "problem" is nonexistent.

**Comment by stoffu** [comment]
Please close this thread as your "problem" is nonexistent.

**Comment by phil2cr** [comment]
"your understanding on how cryptocurrencies work is simply lacking"

I respect your opinion, but i need technical answers.
For example:
For you, how do you find the time it must take (100% chance) to get one block (given the hashrate's pool) ?

**Comment by phil2cr** [comment]
It is not "nonexistent" as mine 21 days at around 8KH/s

no one block found, not even an orphan.

what is the problem with aeon ?

**Comment by stoffu** [comment]
> It is not "nonexistent" as mine 21 days at around 8KH/s

Your estimated block reward frequency at 8KH/s is about 11 days. No block reward after 21 days just means you are a little bit unlucky these days. It's completely normal that you continue to not find any block for the next 20 days. It's also entirely possible that you find the next block in 3 days. That's the nature of mining.
