### ISSUE TITLE
Error: not enough money to transfer

### ISSUE THREAD

**Issue by divra056** [aeonix/aeon-legacy#71]
I have  unlocked balance: 838.300000000000, but can't send all of them to another wallet.

[wallet Wmtarm]: transfer 3 WmspspZifT12TXvvRZUgQbZjm3i3wwDrYZPGiJ5JcaZETKdq8QxLKbFhFaaEttMUt9c61Em6dP1WeHkyDtyRgWf11Q6LvcqqR 838.29
Error: not enough money to transfer, available only 201.170000000000, transaction amount 209.582500000000 = 209.572500000000 + 0.010000000000 (fee)
[wallet Wmtarm]: balance
balance: 838.300000000000, unlocked balance: 838.300000000000
[wallet Wmtarm]: transfer 3 WmspspZifT12TXvvRZUgQbZjm3i3wwDrYZPGiJ5JcaZETKdq8QxLKbFhFaaEttMUt9c61Em6dP1WeHkyDtyRgWf11Q6LvcqqR 838.29
Error: not enough money to transfer, available only 171.930000000000, transaction amount 209.582500000000 = 209.572500000000 + 0.010000000000 (fee)
[wallet Wmtarm]: balance
balance: 838.300000000000, unlocked balance: 838.300000000000
[wallet Wmtarm]: transfer 3 WmspspZifT12TXvvRZUgQbZjm3i3wwDrYZPGiJ5JcaZETKdq8QxLKbFhFaaEttMUt9c61Em6dP1WeHkyDtyRgWf11Q6LvcqqR 838.29
Error: not enough money to transfer, available only 254.700000000000, transaction amount 279.440000000000 = 279.430000000000 + 0.010000000000 (fee)

"available only" is random like is "transaction amount", but not equal my unlocked balance.

And then I let start to guess 

[wallet Wmtarm]: transfer 3 WmspspZifT12TXvvRZUgQbZjm3i3wwDrYZPGiJ5JcaZETKdq8QxLKbFhFaaEttMUt9c61Em6dP1WeHkyDtyRgWf11Q6LvcqqR 800.29
Your transaction needs to be split into 4 transactions.  This will result in a fee of 0.040000000000.  Is this okay?  (Y/Yes/N/No)No
Error: Transaction cancelled.
[wallet Wmtarm]: transfer 3 WmspspZifT12TXvvRZUgQbZjm3i3wwDrYZPGiJ5JcaZETKdq8QxLKbFhFaaEttMUt9c61Em6dP1WeHkyDtyRgWf11Q6LvcqqR 838.20
Error: not enough money to transfer, available only 173.130000000000, transaction amount 209.560000000000 = 209.550000000000 + 0.010000000000 (fee)
[wallet Wmtarm]: transfer 3 WmspspZifT12TXvvRZUgQbZjm3i3wwDrYZPGiJ5JcaZETKdq8QxLKbFhFaaEttMUt9c61Em6dP1WeHkyDtyRgWf11Q6LvcqqR 838.0
Error: not enough money to transfer, available only 159.910000000000, transaction amount 209.510000000000 = 209.500000000000 + 0.010000000000 (fee)
[wallet Wmtarm]: transfer 3 WmspspZifT12TXvvRZUgQbZjm3i3wwDrYZPGiJ5JcaZETKdq8QxLKbFhFaaEttMUt9c61Em6dP1WeHkyDtyRgWf11Q6LvcqqR 838
Error: not enough money to transfer, available only 130.700000000000, transaction amount 167.610000000000 = 167.600000000000 + 0.010000000000 (fee)
[wallet Wmtarm]: transfer 3 WmspspZifT12TXvvRZUgQbZjm3i3wwDrYZPGiJ5JcaZETKdq8QxLKbFhFaaEttMUt9c61Em6dP1WeHkyDtyRgWf11Q6LvcqqR 837
Error: not enough money to transfer, available only 252.410000000000, transaction amount 279.010000000000 = 279.000000000000 + 0.010000000000 (fee)
[wallet Wmtarm]: transfer 3 WmspspZifT12TXvvRZUgQbZjm3i3wwDrYZPGiJ5JcaZETKdq8QxLKbFhFaaEttMUt9c61Em6dP1WeHkyDtyRgWf11Q6LvcqqR 836
Error: not enough money to transfer, available only 275.710000000000, transaction amount 278.676666666668 = 278.666666666668 + 0.010000000000 (fee)
[wallet Wmtarm]: transfer 3 WmspspZifT12TXvvRZUgQbZjm3i3wwDrYZPGiJ5JcaZETKdq8QxLKbFhFaaEttMUt9c61Em6dP1WeHkyDtyRgWf11Q6LvcqqR 835
Error: not enough money to transfer, available only 254.370000000000, transaction amount 278.343333333334 = 278.333333333334 + 0.010000000000 (fee)
[wallet Wmtarm]: transfer 3 WmspspZifT12TXvvRZUgQbZjm3i3wwDrYZPGiJ5JcaZETKdq8QxLKbFhFaaEttMUt9c61Em6dP1WeHkyDtyRgWf11Q6LvcqqR 830
Error: not enough money to transfer, available only 205.840000000000, transaction amount 207.510000000000 = 207.500000000000 + 0.010000000000 (fee)
[wallet Wmtarm]: transfer 3 WmspspZifT12TXvvRZUgQbZjm3i3wwDrYZPGiJ5JcaZETKdq8QxLKbFhFaaEttMUt9c61Em6dP1WeHkyDtyRgWf11Q6LvcqqR 829
Error: not enough money to transfer, available only 201.830000000000, transaction amount 207.260000000000 = 207.250000000000 + 0.010000000000 (fee)
[wallet Wmtarm]: transfer 3 WmspspZifT12TXvvRZUgQbZjm3i3wwDrYZPGiJ5JcaZETKdq8QxLKbFhFaaEttMUt9c61Em6dP1WeHkyDtyRgWf11Q6LvcqqR 810
Your transaction needs to be split into 4 transactions.  This will result in a fee of 0.040000000000.  Is this okay?  (Y/Yes/N/No)NO
Error: Transaction cancelled.
[wallet Wmtarm]: transfer 3 WmspspZifT12TXvvRZUgQbZjm3i3wwDrYZPGiJ5JcaZETKdq8QxLKbFhFaaEttMUt9c61Em6dP1WeHkyDtyRgWf11Q6LvcqqR 820
Your transaction needs to be split into 4 transactions.  This will result in a fee of 0.040000000000.  Is this okay?  (Y/Yes/N/No)No
Error: Transaction cancelled.
[wallet Wmtarm]: transfer 3 WmspspZifT12TXvvRZUgQbZjm3i3wwDrYZPGiJ5JcaZETKdq8QxLKbFhFaaEttMUt9c61Em6dP1WeHkyDtyRgWf11Q6LvcqqR 825
Error: not enough money to transfer, available only 267.210000000000, transaction amount 275.010000000000 = 275.000000000000 + 0.010000000000 (fee)
[wallet Wmtarm]: transfer 3 WmspspZifT12TXvvRZUgQbZjm3i3wwDrYZPGiJ5JcaZETKdq8QxLKbFhFaaEttMUt9c61Em6dP1WeHkyDtyRgWf11Q6LvcqqR 824
Error: not enough money to transfer, available only 203.210000000000, transaction amount 206.010000000000 = 206.000000000000 + 0.010000000000 (fee)
[wallet Wmtarm]: transfer 3 WmspspZifT12TXvvRZUgQbZjm3i3wwDrYZPGiJ5JcaZETKdq8QxLKbFhFaaEttMUt9c61Em6dP1WeHkyDtyRgWf11Q6LvcqqR 823
Your transaction needs to be split into 4 transactions.  This will result in a fee of 0.040000000000.  Is this okay?  (Y/Yes/N/No)No
Error: Transaction cancelled.

WFT? Why I can't send all of my coins? How to calculate fee and amount and send all in one transaction?

**Comment by stoffu** [comment]
Most likely you can't send all your remaining balance in a single tx since it would be too big; the wallet needs to generate multiple txes, as you can see when you specified smaller amounts for transfer.

What's happening with the "available only" error is probably that some of the split txes will lock some of your balance, just like any other usual transfer where some of your balance gets locked until the tx gets mined and your change output gets unlocked. In your case, some of the split txes created earlier lock some large portion of your balance, making your unlocked balance insufficient to create the remaining split txes.

I believe this is an inherent limitation for any coins (including Bitcoin & Monero) and there is no easy fix, although the error message could have been a bit more informative. You just need to do money transfer multiple times with smaller amounts.

**Comment by L7788** [comment]
It's unbelievable, sending 838.3 Aeon failed unless split this small amount of money into multiple pieces and send separately? 838 coins are not huge at all. What's the inherent limitation for Aeon coin?

**Comment by sammy007** [comment]
There is no limitation. Send `amount - 1` for now, everything will be fixed in next few weeks by rebase. The split is normal tho.

**Comment by L7788** [comment]
Did you mean send more than 1 coin is unsafe prior to the rebase? 

Assume if I want to send over thousands of coins from my local aeon wallet to an exchange. What's the safe way to do so (maximum qty per send)? If only 1 coin per transfer is safe, it means it's malfunction because it is useless. 

Sorry, don't understand why split is normal unless i send coins to multiple addresses, I need to split them for each address and send them via multiple txes.

**Comment by sammy007** [comment]
I meant send 837 instead. You got many small chunks so tx size is big and must be splitted. If you will send a little bit less than whole balance you shouldn't get any errors bc there will be enough for fees.

**Comment by L7788** [comment]
Clear! Thanks

**Comment by stoffu** [comment]
@sammy007 
> everything will be fixed in next few weeks by rebase.

I don't think this issue has anything to do with the rebase; the exact same limitation applies to Monero. If one has numerous outputs of fractional amounts and wants to spend all of them, it cannot ever possibly be done in a single tx due to the tx size limit, and needs to be split into multiple txes, which sometimes causes this "not enough money" error due to the change being unconfirmed.

@iamsmooth 
Could you comment on this?

**Comment by iamsmooth** [comment]
@stuffu I agree with your assessment. It is possible there are better algorithms in newer Monero for splitting that produce less change and therefore reduce such problems, but it still can't be completely avoided.

**Comment by sammy007** [comment]
@stoffu at least there will be consistent errors AFAIK unlike in OP when you are getting random amounts/fees.

**Comment by stoffu** [comment]
@sammy007 Thanks, I didn't know about that as I haven't checked the code so closely.

**Comment by sammy007** [comment]
Me too, just from my user experience.

**Comment by divra056** [comment]
today I try to send some coins from my wallet, not 800, 700 or many hundreds, just 289 coins, but see it again: "Error: not enough money to transfer"
![aeon](https://user-images.githubusercontent.com/29574387/31860457-fa144a2a-b722-11e7-90a2-fd240b2e23ca.png)
I try to guess how to send only 200 coins  - It is easy for 12 blocks and commissions x12 for this operations :)  Very useful coin!

**Comment by stoffu** [comment]
@divra056 It's not the total amount of coins that matters; what matters is the size of the transaction, which is determined by the number of inputs. What do you see when you type `incoming_transfers available` in simplewallet? If you see many lines of amounts like 0.1, probably you won't be able to send them all at once.

**Comment by aeonix** [comment]
Appears to be intended behavior of the code and the user's issue was resolved

**Comment by stoffu** [comment]
If something happens to smooth, someone can fork the repo and move on. There is no power centralized around him; if you want to make any changes, send pull requests.

I really don’t understand what problem people have presently. This thread is starting to become nonsense to me.

It’s not that I’m against the idea in fear of someone with write access destroying the repository. I’m against it simply because the idea seems nonsensical. Nonsensical behavior makes the Aeon community look dumb.

**Comment by sci-comp** [comment]
@fluffypony: forking the repo and providing an alternate implementation should not be on the table for consideration.
