### ISSUE TITLE
Please backport getblocktemplate#prev_hash from Monero

### ISSUE THREAD

**Issue by sammy007** [aeonix/aeon-legacy#72]
I am sure @Arux-BTT can help with it. This is must have for pools.

**Comment by myaeon-ru** [comment]
Network hashrate doubled! In one day from 8MH to 18MH) I believe "investors" come ))))
Like in march of this year ) Network hashrate was about 28-40MH and after v1 dropped to 10

**Comment by exty357** [comment]
> Do you have any links to cnv7 asic miners? They must not be publicly available right now because nobody can seem to provide any purchasing information.

No I do not have links)
Of course, they are not for sale. 

The current situation is completely similar to the beginning of this year.
A sharp increase in the hashrate of monero network began in early January (see on https://xmr.ru/charts/hashrate).
But bitmain started selling CN-ASIC's only on March 17, at that moment when no one doubted their existence.

The future progress of Aeon is gonna be sad/upsetting.
Turtlecoin is sheduled for hardfork after 20 January and all the 70 mhs from their network will move to Aeon because it has no choice/other way. 

It is the reason why PoW needs to start changing right NOW.

**Comment by BigslimVdub** [comment]
> Looks like there's a proposal over in #95

For CN-Turtle yes, not for CNv8.
