### ISSUE TITLE
Why is AEON wallet not working on Bittrex?

### ISSUE THREAD

**Issue by wlhjkl** [aeonix/aeon-legacy#76]
Withdrawals and deposits for AEON are disabled on Bittrex, while trading works. Is there actual maintenance going on? Are developers in contact with Bittrex? When do you expect this problem to be fixed?

**Comment by wyattp11** [comment]
Check out [Aeon](https://www.reddit.com/r/Aeon/) for answers to all your questions.

**Comment by L7788** [comment]
I am feeling very sad. When I deposit my Aeon coins to to Bittrex. The Bittrex exchange system gave error message "wallet is maintainance" and it cannot work at all. I didn't realize there is a such problem at all. Why Bittrex lists Aeon coin but wallet is disabled. I really want to cry!!!!! Does anyone know when Dev can fix this problem? We are still supporters of the Aeon community. But this problem really needs to be fixed if Dev still care about their supporters.

**Comment by wyattp11** [comment]
If you need to sell coins, you can use HitBTC, the wallet is functional there. This really isn't the appropriate place to whine and complain, go to the subreddit.

**Comment by sanitariu** [comment]
"This really isn't the appropriate place to whine and complain"
I think this is exactly the right place for the developer to answer what bittrex want.
What kind of fixes he need to do.
Keeping people in the unknown field for 3 months is not good.
If the coin do not have developer it means its dead and we must sell and run away.
This is the official git source code repo for AEON coin.
Developers please tell us what you need to fix ? May be someone can help even me !

**Comment by wyattp11** [comment]
Go read the Aeon subreddit and calm down. Code rebase doesn't happen overnight.

**Comment by sanitariu** [comment]
I can not find information why we need code rebase ?
Why developers does not want help ?

**Comment by wyattp11** [comment]
Look harder. Nobody is going to do it for you. Once again, GitHub is a code repository... not a forum for you to complain about investment decisions. If you have a legitimate issue with the code, bring it forth... otherwise please mark this thread closed.

**Comment by sanitariu** [comment]
Hi, do not get me wrong. I do not own AEONs at any place. I just want to help. But seems like someone somewhere on his own is trying to do something alone in a secret. 
The correct way for the devs is to say something like: Look people bittrex said our code have bad stuff here or here and we need to fix it as soon as possible so they can open our wallet. If anyone want to help lets code. And of course the best way is to fill issue here and assign someone to solve it  instead writing to some forums somewhere something. What do you think ?

**Comment by sanitariu** [comment]
Ok i noticed something strange. How is this possible ? AEON supply increases on bittrex ! The price there is 0.00024194 but the price on hitbtc is 0.00016384. So only logical thing is that somehow someone is buying on hitbtc at 0.00016384 then somehow he transfers to his wallet at bittrext and 
sells at 0.00024194. Call me crazy I do not know but seems pretty good reason we do not need wallets working at bittrex :)

**Comment by sammy007** [comment]
@sanitariu could you stop spreading nonsense in an issue tracker?

There is no deposits and withdrawals on bittrex so price higher because of demand. On Hitbtc you can deposit and dump so miners unloading there and price is lower. Someone with funds on bittrex dumping there and buying back on hitbtc. I would do the same.

**Comment by sanitariu** [comment]
Yes of course. I need developer opinion on what kind of help he need so wallet can be opened.
I may have the resources even programmers so issue is resolved very quick.
But we need information. This - "we are making core rebase" does not fit in any programmers plan.

**Comment by sammy007** [comment]
Developer is working on rebase. You can help if you are a professional cryptograph or very skilled C++ dev.

**Comment by sanitariu** [comment]
Yes i can help. How to contact him ? He does not answer here on the hub. This issue is from 17 days also there are other issues. If he is serious dropping an answers here takes 5 minutes per day. Also roadmap is missing and other stuff. May be if dev says what is the plan me and others can help a lot more.

**Comment by stoffu** [comment]
The core developer @iamsmooth is also a member of the Monero Core Team where he contributes a lot there, too. This is just my guess, but it's quite possible that Monero is of a much higher priority for him compared to Aeon due to the rapidly growing attention and new events/incidents/discussions happening every day. He does state that Aeon's rebase is close to completion, and we take his word for it without any doubt because of his past contributions to Aeon which are truly tremendous.

If you're uncomfortable with this situation, probably Aeon isn't a good fit for you.

**Comment by alleyvolta** [comment]
Can this be closed now, as there was never a code issue in the first place? Git is for error reporting and debugging only. @sanitariu if you have that many resources and that much experience why not start your own coin? Sounds a lot easier than trying to collaborate with someone you haven't given any reason to collaborate with you.

**Comment by aeonix** [comment]
Agree with @alanVitullo
